<?php

// Template Name: Producers

get_header();

$producers_args = array(

    'post_type' => 'ourproducer',

    'post_status' => 'publish',

    'posts_per_page' => 3,

    'orderby' => 'date',

    'order' => 'ASC',

);

$producers_query = new WP_Query($producers_args);
$count = wp_count_posts($post_type = 'ourproducer');

?>
<!-------------------------------- Producers Start ------------------------------------>
<section class="section-producers">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <span class="producers-tagline d-block">Lorem Ipsum</span>
                <h2 class="producers-title">our producers</h2>
                <p class="producers-text">&dash; Lorem Ipsum it is a long established fact that a reader will be distracted by the readable.</p>
            </div>
        </div>
        <div class="row gy-4 gy-xl-0">
            <div class="col-md-6 col-lg-3">
                <div class="producers-media">
                    <div class="icon">
                        <img src="<?= get_template_directory_uri(); ?>/assets/images/icon_quality.png" alt="icon">
                    </div>
                    <div class="content">
                        <p class="mb-0">quality</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="producers-media">
                    <div class="icon">
                        <img src="<?= get_template_directory_uri(); ?>/assets/images/icon_auth.png" alt="icon">
                    </div>
                    <div class="content">
                        <p class="mb-0">authenticity</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="producers-media">
                    <div class="icon">
                        <img src="<?= get_template_directory_uri(); ?>/assets/images/icon_fresh.png" alt="icon">
                    </div>
                    <div class="content">
                        <p class="mb-0">freshness</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="producers-media">
                    <div class="icon">
                        <img src="<?= get_template_directory_uri(); ?>/assets/images/icon_sustain.png" alt="icon">
                    </div>
                    <div class="content">
                        <p class="mb-0">Sustainability</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row my-4">
            <div class="col-md-10 mx-auto">
                <hr class="hr-line">
            </div>
        </div>
        <div class="row gy-4" id="producers_list">
            <?php if ($producers_query->have_posts()) : ?>

                <?php foreach ($producers_query->posts as $key => $producer) :

                    $producer_img = wp_get_attachment_url(get_post_thumbnail_id($producer->ID));

                    $producer_meta = get_post_meta($producer->ID);

                ?>
                    <div class="col-md-6 col-lg-4">
                        <a href="<?= get_permalink($producer->ID); ?>">
                            <div class="producers-card">
                                <img src="<?= $producer_img; ?>" alt="producer" class="img-producer">
                                <p class="inner_a"><?= $producer->post_title; ?></p>
                            </div>
                        </a>
                    </div>

            <?php endforeach;
            endif; ?>

        </div>
        <?php if ($count->publish > 3) : ?>
            <div class="row">
                <div class="col text-center mt-60">
                    <button class="btn btn-more" id="load_more_producer">see more</button>

                </div>
            </div>
        <?php endif; ?>
    </div>
    <div class="loader">

        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: transparent; display: block; shape-rendering: auto;" width="144px" height="144px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <circle cx="50" cy="50" r="28" stroke-width="7" stroke="#912623" stroke-dasharray="43.982297150257104 43.982297150257104" fill="none" stroke-linecap="round">
                <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="1.4492753623188404s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
            </circle>
            <!-- [ldio] generated by https://loading.io/ -->
        </svg>
    </div>
</section>
<!-------------------------------- Producers End ------------------------------------>
<?php get_footer(); ?>